"""Import cohesive route modules whose decorators register the complete API."""

from portal_backend import (
    active_conversation_routes,
    agent_digest_routes,
    agent_event_routes,
    agent_model_routes,
    agent_notification_routes,
    agent_profile_routes,
    agent_reachability_routes,
    agent_registration_routes,
    agent_request_box_routes,
    agent_self_wake_routes,
    agent_suggestion_routes,
    agent_task_claim_routes,
    agent_wake_policy_routes,
    attachment_routes,
    container_control_routes,
    container_event_routes,
    container_lifecycle,
    container_lifecycle_routes,
    container_pairing_routes,
    container_request_list_routes,
    container_snapshot_routes,
    container_task_list_routes,
    container_token_usage_routes,
    conversation_read_routes,
    conversation_write_routes,
    dashboard_routes,
    decision_routes,
    embodiment_token_routes,
    llm_key_routes,
    model_setting_routes,
    onboarding_routes,
    orphan_lease_routes,
    persona_protocol_routes,
    provider_key_routes,
    request_acceptance_routes,
    request_close_routes,
    request_conversion_routes,
    request_creation_routes,
    request_nudge_routes,
    request_rejection_routes,
    request_resolution_routes,
    request_response_routes,
    task_assignment_routes,
    task_cancellation_routes,
    task_creation_routes,
    task_dispatch_routes,
    task_done_routes,
    task_impact_routes,
    task_message_routes,
    task_protocol_routes,
    task_verification_routes,
    terminal_config_routes,
    wake_acknowledgement_routes,
    wake_lease_claim_routes,
    wake_lease_renewal_routes,
    wake_scan_routes,
    worker_run_finish_routes,
    worker_run_read_routes,
    worker_run_start_routes,
)

ROUTE_MODULES = (
    active_conversation_routes,
    agent_digest_routes,
    agent_event_routes,
    agent_model_routes,
    agent_notification_routes,
    agent_profile_routes,
    agent_reachability_routes,
    agent_registration_routes,
    agent_request_box_routes,
    agent_self_wake_routes,
    agent_suggestion_routes,
    agent_task_claim_routes,
    agent_wake_policy_routes,
    attachment_routes,
    container_control_routes,
    container_event_routes,
    container_lifecycle,
    container_lifecycle_routes,
    container_pairing_routes,
    container_request_list_routes,
    container_snapshot_routes,
    container_task_list_routes,
    container_token_usage_routes,
    conversation_read_routes,
    conversation_write_routes,
    dashboard_routes,
    decision_routes,
    embodiment_token_routes,
    llm_key_routes,
    model_setting_routes,
    onboarding_routes,
    orphan_lease_routes,
    persona_protocol_routes,
    provider_key_routes,
    request_acceptance_routes,
    request_close_routes,
    request_conversion_routes,
    request_creation_routes,
    request_nudge_routes,
    request_rejection_routes,
    request_resolution_routes,
    request_response_routes,
    task_assignment_routes,
    task_cancellation_routes,
    task_creation_routes,
    task_dispatch_routes,
    task_done_routes,
    task_impact_routes,
    task_message_routes,
    task_protocol_routes,
    task_verification_routes,
    terminal_config_routes,
    wake_acknowledgement_routes,
    wake_lease_claim_routes,
    wake_lease_renewal_routes,
    wake_scan_routes,
    worker_run_finish_routes,
    worker_run_read_routes,
    worker_run_start_routes,
)


def compatibility_export(name):
    """Resolve a legacy ``main`` attribute from its responsibility module."""
    for module in ROUTE_MODULES:
        if hasattr(module, name):
            return getattr(module, name)
    raise AttributeError(name)


__all__ = [
    "agent_model_routes",
    "agent_registration_routes",
    "compatibility_export",
    "persona_protocol_routes",
    "request_acceptance_routes",
    "task_done_routes",
    "task_verification_routes",
]
