import path from 'node:path'
import { dockerExec, type Exec } from './dockerExec'
import { renderCompose } from './templates'
import type {
  BridgeError,
  ProgressEvent,
  ProvisionOptions,
  ProvisionResult,
  ProvisionStep
} from '../shared/types'

/** Minimal fs surface the engine needs, injectable for tests. */
export interface EngineFs {
  readFile(p: string): string
  writeFile(p: string, c: string): void
  copyTree(src: string, dst: string): void
  mkdirp(p: string): void
  chmod(p: string, mode: number): void
  exists(p: string): boolean
}

export type FetchJson = (url: string, init?: { method?: string; body?: unknown }) => Promise<unknown>

export interface EngineDeps {
  exec: Exec
  fetchJson: FetchJson
  fs: EngineFs
  templatesRoot: () => string
  findFreePort: (start: number) => number
  readComposeTemplate: () => string
  genSecret: () => string
  user: string
  waitPortalTimeoutMs?: number
  waitPortalPollMs?: number
}

const STDERR_TAIL = 500
const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms))

function fail(step: ProvisionStep, code: BridgeError['code'], detail: string): never {
  if (code === 'PROVISION_FAILED') {
    throw { code, step, stderr: detail.slice(-STDERR_TAIL) } as const
  }
  throw { code, detail } as unknown as BridgeError
}

/** docker compose -f <composeFile> <args...> from the project's .orcha dir. */
async function compose(exec: Exec, orchaDir: string, args: string[]): Promise<string> {
  const file = path.join(orchaDir, 'docker-compose.yml')
  const res = await exec('docker', ['compose', '-f', file, ...args])
  return res.stdout
}

export async function provision(
  opts: ProvisionOptions,
  onProgress: (e: ProgressEvent) => void,
  deps: EngineDeps
): Promise<ProvisionResult> {
  const runId = `${opts.folder}:${opts.mode}:${Date.now()}`
  const emit = (step: ProvisionStep, status: ProgressEvent['status'], extra?: Partial<ProgressEvent>): void =>
    onProgress({ runId, step, status, ...(extra as object) } as ProgressEvent)

  const { fs } = deps
  const orchaDir = path.join(opts.folder, '.orcha')
  const claudeDir = path.join(opts.folder, '.claude')
  const configPath = path.join(claudeDir, 'orcha.json')
  const warnings: string[] = []

  // Resolve project name + ports. upgrade preserves from orcha.json; init/reset pick fresh.
  let projectName: string
  let apiPort: number
  let dbPort: number
  let bridgePort: number
  if (opts.mode === 'upgrade') {
    const cfg = JSON.parse(fs.readFile(configPath)) as Record<string, number | string>
    projectName = String(cfg.project_name)
    apiPort = Number(cfg.api_port)
    dbPort = Number(cfg.db_port)
    bridgePort = Number(cfg.bridge_port) || deps.findFreePort(8765)
  } else {
    projectName = opts.name ?? path.basename(opts.folder)
    dbPort = deps.findFreePort(5432)
    apiPort = deps.findFreePort(8000)
    bridgePort = deps.findFreePort(8765)
  }
  const apiBase = `http://localhost:${apiPort}`
  const project = `orcha-${projectName}`

  // reset: wipe the volume FIRST (explicit only).
  if (opts.mode === 'reset') {
    try {
      await compose(deps.exec, orchaDir, ['down', '-v'])
    } catch {
      // a not-yet-existing stack down -v is fine; continue.
    }
  }

  // 1. render compose
  emit('render-compose', 'start')
  const rendered = renderCompose(deps.readComposeTemplate(), { projectName, dbPort, apiPort, bridgePort })
  fs.mkdirp(orchaDir)
  fs.writeFile(path.join(orchaDir, 'docker-compose.yml'), rendered)
  emit('render-compose', 'ok')

  // 2. copy templates (migrations/, portal/, skills, prefs) + ensure secret + bind dirs
  emit('copy-templates', 'start')
  const root = deps.templatesRoot()
  fs.copyTree(path.join(root, 'migrations'), path.join(orchaDir, 'migrations'))
  fs.copyTree(path.join(root, 'portal'), path.join(orchaDir, 'portal'))
  // .env secret (mirrors _ensure_secret_key): write only if absent.
  const envFile = path.join(orchaDir, '.env')
  if (!fs.exists(envFile)) {
    fs.writeFile(envFile, `# Generated by Orcha — secrets for docker compose. Do NOT commit.\nORCHA_SECRET_KEY=${deps.genSecret()}\n`)
    fs.chmod(envFile, 0o600)
  }
  // pre-create host bind dirs so Linux doesn't bind-create them as root.
  fs.mkdirp(path.join(claudeDir, '.orcha-wakes'))
  fs.mkdirp(path.join(claudeDir, '.orcha-attachments'))
  // write/refresh orcha.json
  fs.mkdirp(claudeDir)
  const config: Record<string, unknown> = {
    api_base_url: apiBase,
    project_name: projectName,
    api_port: apiPort,
    db_port: dbPort,
    bridge_port: bridgePort
  }
  if (opts.mode === 'upgrade' && fs.exists(configPath)) {
    const prev = JSON.parse(fs.readFile(configPath)) as Record<string, unknown>
    if (prev.current_container_id) config.current_container_id = prev.current_container_id
  }
  fs.writeFile(configPath, JSON.stringify(config, null, 2) + '\n')
  emit('copy-templates', 'ok')

  // 3. compose up -d --build (stream stdout lines)
  emit('compose-up', 'start')
  try {
    const out = await compose(deps.exec, orchaDir, ['up', '-d', '--build'])
    for (const line of out.split('\n').filter(Boolean)) emit('compose-up', 'log', { line })
    emit('compose-up', 'ok')
  } catch (err) {
    const stderr = String((err as { stderr?: string }).stderr ?? (err as Error).message)
    emit('compose-up', 'fail', { code: 'PROVISION_FAILED', detail: stderr })
    fail('compose-up', 'PROVISION_FAILED', stderr)
  }

  // 4. wait for portal
  emit('wait-portal', 'start')
  const timeout = deps.waitPortalTimeoutMs ?? 30000
  const poll = deps.waitPortalPollMs ?? 500
  const deadline = Date.now() + timeout
  let portalUp = false
  while (Date.now() < deadline) {
    try {
      await deps.fetchJson(`${apiBase}/`)
      portalUp = true
      break
    } catch {
      await sleep(poll)
    }
  }
  if (!portalUp) {
    emit('wait-portal', 'fail', { code: 'PORTAL_TIMEOUT', detail: `no 200 from ${apiBase}/ in ${timeout}ms` })
    fail('wait-portal', 'PORTAL_TIMEOUT', 'portal did not come up')
  }
  emit('wait-portal', 'ok')

  // 5. create container (skip on upgrade)
  let containerId: string | undefined
  if (opts.mode === 'upgrade') {
    emit('create-container', 'skip')
  } else {
    emit('create-container', 'start')
    const objective = (opts.objective ?? '').trim() || path.basename(opts.folder)
    try {
      const data = (await deps.fetchJson(`${apiBase}/api/containers`, {
        method: 'POST',
        body: { name: objective }
      })) as { container_id: string }
      containerId = data.container_id
      config.current_container_id = containerId
      fs.writeFile(configPath, JSON.stringify(config, null, 2) + '\n')
      emit('create-container', 'ok')
    } catch (err) {
      const msg = (err as Error).message
      const status = (err as { status?: number }).status
      if (status === 409 || /already has a container|409/.test(msg)) {
        emit('create-container', 'fail', { code: 'CONTAINER_EXISTS', detail: msg })
        fail('create-container', 'CONTAINER_EXISTS', msg)
      }
      emit('create-container', 'fail', { code: 'PROVISION_FAILED', detail: msg })
      fail('create-container', 'PROVISION_FAILED', msg)
    }
  }

  // 6. register first human (non-fatal; skip on upgrade)
  if (opts.mode === 'upgrade' || !containerId) {
    emit('register-human', 'skip')
  } else {
    emit('register-human', 'start')
    const alias = (opts.alias ?? deps.user ?? 'operator').trim() || 'operator'
    try {
      await deps.fetchJson(`${apiBase}/api/containers/${containerId}/agents`, {
        method: 'POST',
        body: { alias, role: 'operator', kind: 'human' }
      })
      emit('register-human', 'ok')
    } catch (err) {
      warnings.push(`human registration failed (${(err as Error).message}); register later in the portal`)
      emit('register-human', 'ok') // non-fatal: report ok with a warning surfaced separately
    }
  }

  // 7. start daemons — the desktop app cannot run the host CLI daemons (Python
  //    processes the CLI spawns). The stack + container + portal (incl. its
  //    in-container workers) are fully provisioned, which is what onboarding needs.
  //    Emit 'skip' honestly — we did not start anything here — and surface a warning.
  emit('start-daemons', 'skip')
  warnings.push('Host notifier/bridge daemons are started by the CLI; the desktop app relies on the portal. Run `orcha up` in a terminal if you need the host daemons.')

  return { project, apiPort, warnings }
}
