#!/usr/bin/env python3
"""One-command GitHub setup for an Orcha Cloud box — no manual OAuth-app clicking.

Drives GitHub's App-manifest flow (the only programmatic way to create an app):

    python3 deploy/setup-github.py \
        --domain orcha.example.com --acme-email you@example.com \
        --users hussein-quant,teammate --stack-network orcha-dogfood_default

1. Opens your browser on a local page that auto-submits the app manifest to
   GitHub (use --org <name> to create the app under an organization).
2. You click ONE button ("Create GitHub App") on github.com.
3. GitHub redirects back with a one-time code; this script exchanges it for
   the app's credentials (client id/secret, private key, webhook secret).
4. Writes deploy/auth/.env (complete — cookie secret and team bearer token
   are generated too) plus github-app.json / github-app.pem for the future
   repo-access work (clone tokens, PR-as-bot).

Run this on your LAPTOP (it needs a browser), then copy the .env to the box:

    scp deploy/auth/.env <box>:/opt/orcha-cloud/deploy/auth/.env

Stdlib only; nothing is sent anywhere except to github.com.
"""
from __future__ import annotations

import argparse
import http.server
import json
import pathlib
import secrets
import sys
import threading
import urllib.request
import webbrowser

HERE = pathlib.Path(__file__).resolve().parent
AUTH_DIR = HERE / "auth"


def build_manifest(args) -> dict:
    return {
        "name": args.name,
        "url": f"https://{args.domain}",
        "redirect_url": f"http://localhost:{args.port}/callback",
        "callback_urls": [f"https://{args.domain}/oauth2/callback"],
        # MUST be public: a private GitHub App 404s the OAuth authorize step for
        # every account except its owner — invited members could never sign in.
        "public": True,
        # Sign-in works with just the client credentials; these permissions
        # pre-provision the same app for repo access (sub-project 3: clone
        # tokens + PR-as-bot) so ONE app serves both.
        "default_permissions": {
            # write: agents push branches and open PRs as the app bot — read-only
            # stops at the push (field-found).
            "contents": "write",
            "metadata": "read",
            "pull_requests": "write",
            # agents file findings as GitHub issues too ("create issues for what
            # you found") — absent, `gh issue create` 403s (field-found).
            "issues": "write",
        },
        "default_events": [],
    }


def submit_page(manifest: dict, org: str | None) -> bytes:
    action = (f"https://github.com/organizations/{org}/settings/apps/new"
              if org else "https://github.com/settings/apps/new")
    payload = json.dumps(manifest).replace("&", "&amp;").replace("'", "&#39;")
    return f"""<!doctype html><meta charset="utf-8">
<title>Orcha — create GitHub App</title>
<body style="font-family: system-ui; max-width: 40rem; margin: 4rem auto;">
<h2>Redirecting to GitHub…</h2>
<p>Click <b>Create GitHub App</b> on the next page. That's the only step.</p>
<form id="f" method="post" action="{action}">
  <input type="hidden" name="manifest" value='{payload}'>
  <noscript><button>Continue to GitHub</button></noscript>
</form>
<script>document.getElementById("f").submit()</script>
</body>""".encode()


def exchange(code: str) -> dict:
    req = urllib.request.Request(
        f"https://api.github.com/app-manifests/{code}/conversions",
        method="POST",
        headers={"Accept": "application/vnd.github+json",
                 "User-Agent": "orcha-cloud-setup"},
        data=b"",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def write_outputs(app: dict, args) -> None:
    AUTH_DIR.mkdir(parents=True, exist_ok=True)
    env_path = AUTH_DIR / ".env"
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    values = {
        "ORCHA_DOMAIN": args.domain,
        "ACME_EMAIL": args.acme_email,
        "ORCHA_STACK_NETWORK": args.stack_network,
        "GITHUB_CLIENT_ID": app["client_id"],
        "GITHUB_CLIENT_SECRET": app["client_secret"],
        "ALLOWED_GITHUB_USERS": args.users,
        "COOKIE_SECRET": existing.get("COOKIE_SECRET") or secrets.token_urlsafe(32),
        "ORCHA_TEAM_TOKEN": existing.get("ORCHA_TEAM_TOKEN") or secrets.token_urlsafe(32),
    }
    env_path.write_text(
        "# Generated by deploy/setup-github.py — never commit this file.\n"
        + "".join(f"{k}={v}\n" for k, v in values.items())
    )
    env_path.chmod(0o600)

    meta = {k: app[k] for k in ("id", "slug", "html_url", "owner") if k in app}
    (AUTH_DIR / "github-app.json").write_text(json.dumps(meta, indent=2, default=str) + "\n")
    pem = AUTH_DIR / "github-app.pem"
    pem.write_text(app["pem"])
    pem.chmod(0o600)
    if app.get("webhook_secret"):
        wh = AUTH_DIR / "github-app.webhook-secret"
        wh.write_text(app["webhook_secret"] + "\n")
        wh.chmod(0o600)

    print(f"""
✓ GitHub App created: {app.get('html_url', app['slug'])}
✓ Wrote {env_path}  (cookie secret + team bearer token generated)
✓ Wrote github-app.json / github-app.pem  (repo-access credentials, for later)

Next:
  scp {env_path} <box>:/opt/orcha-cloud/deploy/auth/.env
  ssh <box> 'cd /opt/orcha-cloud/deploy/auth && docker compose --env-file .env -f docker-compose.auth.yml up -d'

Your team bearer token (iOS app / API callers):
  {values['ORCHA_TEAM_TOKEN']}
""")


class Handler(http.server.BaseHTTPRequestHandler):
    manifest: dict = {}
    org: str | None = None
    result: dict = {}
    done = threading.Event()

    def do_GET(self):  # noqa: N802
        if self.path.startswith("/callback"):
            from urllib.parse import parse_qs, urlparse
            code = parse_qs(urlparse(self.path).query).get("code", [None])[0]
            if not code:
                self.send_error(400, "missing code")
                return
            try:
                Handler.result = exchange(code)
            except Exception as e:  # surfaced in terminal; browser gets a plain error
                self.send_error(502, f"exchange failed: {e}")
                Handler.done.set()
                return
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(b"<body style='font-family:system-ui;margin:4rem'>"
                             b"<h2>Done \xe2\x9c\x93</h2><p>Credentials captured &mdash; "
                             b"return to your terminal. You can close this tab.</p></body>")
            Handler.done.set()
        else:
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(submit_page(Handler.manifest, Handler.org))

    def log_message(self, *a):  # keep the terminal clean
        pass


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--domain", required=True, help="public hostname, e.g. orcha.example.com")
    ap.add_argument("--acme-email", required=True)
    ap.add_argument("--users", required=True,
                    help="comma-separated GitHub usernames allowed into the portal")
    ap.add_argument("--stack-network", required=True,
                    help="the box's orcha compose network, e.g. orcha-dogfood_default")
    ap.add_argument("--name", default=None, help="GitHub App name (default: orcha-<domain>)")
    ap.add_argument("--org", default=None, help="create the app under this GitHub org")
    ap.add_argument("--port", type=int, default=8971)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the manifest and exit (no browser, no server)")
    args = ap.parse_args()
    args.name = args.name or f"orcha-{args.domain.split('.')[0]}-{secrets.token_hex(2)}"

    manifest = build_manifest(args)
    if args.dry_run:
        print(json.dumps(manifest, indent=2))
        return 0

    Handler.manifest, Handler.org = manifest, args.org
    srv = http.server.HTTPServer(("127.0.0.1", args.port), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    url = f"http://localhost:{args.port}/"
    print(f"Opening {url} — click 'Create GitHub App' on the GitHub page…")
    webbrowser.open(url)
    if not Handler.done.wait(timeout=600):
        print("Timed out after 10 minutes — rerun when ready.", file=sys.stderr)
        return 1
    srv.shutdown()
    if not Handler.result:
        print("GitHub exchange failed — see the browser tab / rerun.", file=sys.stderr)
        return 1
    write_outputs(Handler.result, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
