"""Dotenv-file primitives for the `orcha` CLI.

Read / append / mode-clamp helpers for ``.orcha/.env`` (the file docker compose
interpolates secrets from). Split out of ``__main__`` as a self-contained group;
``__main__`` re-imports these names, so ``orcha_cli.__main__.<fn>`` references and
the secret-key provenance tests that call them keep resolving unchanged.

The mode-clamp (0600) is applied after EVERY append — including when the file
pre-existed at a laxer mode — because we just wrote a secret into it.
"""
from __future__ import annotations

import pathlib
from typing import Optional


def _read_env_file_value(env_file: pathlib.Path, name: str) -> Optional[str]:
    """Read ``NAME=value`` from a dotenv-style file (first match wins). None if absent/unreadable."""
    try:
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            if k.strip() == name:
                return v.strip()
    except OSError:
        return None
    return None


def _append_env_file(env_file: pathlib.Path, name: str, value: str) -> None:
    """Append ``NAME=value`` to ``.orcha/.env``, creating it 0600. Raises OSError on failure.

    The file holds secrets for compose interpolation, so its mode is clamped to 0600 after
    EVERY append — including when it pre-existed at a laxer mode (e.g. a hand-created 0644 .env
    that now gathers a generated ORCHA_SECRET_KEY). Clamping only on creation would leave a
    world-readable secret on disk, contradicting the 0600 we advertise."""
    env_file.parent.mkdir(parents=True, exist_ok=True)
    existed = env_file.exists()
    with env_file.open("a", encoding="utf-8") as fh:
        if not existed:
            fh.write("# Generated by `orcha` — secrets for docker compose interpolation. "
                     "Do NOT commit.\n")
        fh.write(f"{name}={value}\n")
    # Clamp to 0600 whether or not the file pre-existed — we just wrote a secret into it.
    _tighten_env_file(env_file)


def _tighten_env_file(env_file: pathlib.Path) -> None:
    """Clamp ``.orcha/.env`` to 0600. Best-effort: a missing file or chmod failure (e.g. an
    unsupported filesystem) is swallowed — the env holds secrets but losing the tightening must
    not break ``up``."""
    try:
        env_file.chmod(0o600)
    except OSError:
        pass
