import Foundation

// The app↔widget contract: the app (foreground refresh + background sweep)
// writes a compact per-workspace state into the App Group; the widget only
// ever reads it. Kept dependency-free — this file compiles into both targets.

struct WidgetAgent: Codable, Hashable {
    let alias: String
    let status: String
}

struct WidgetWorkspace: Codable, Identifiable, Hashable {
    let id: String
    let name: String
    let verify: Int
    let plans: Int
    let escalations: Int
    let agents: [WidgetAgent]
    /// On-device Decision Assist headline, generated by the APP (never by the
    /// widget process — widgets can't afford inference); nil when Apple
    /// Intelligence is off or generation failed.
    let headline: String?
    let updatedAt: Date

    var needsYou: Int { verify + plans + escalations }
}

enum WidgetStore {
    static let appGroup = "group.io.openorcha.mobile"
    private static let key = "orcha_widget_state"

    /// Most-recently-viewed workspace first — the widget's primary.
    static func load() -> [WidgetWorkspace] {
        guard let defaults = UserDefaults(suiteName: appGroup),
              let data = defaults.data(forKey: key) else { return [] }
        return (try? JSONDecoder().decode([WidgetWorkspace].self, from: data)) ?? []
    }

    static func save(_ workspaces: [WidgetWorkspace]) {
        guard let defaults = UserDefaults(suiteName: appGroup),
              let data = try? JSONEncoder().encode(workspaces) else { return }
        defaults.set(data, forKey: key)
    }

    /// Upsert one workspace to the front (most-recent-first ordering).
    static func update(_ workspace: WidgetWorkspace) {
        var all = load().filter { $0.id != workspace.id }
        all.insert(workspace, at: 0)
        save(Array(all.prefix(8)))
    }
}
