-- Orcha SQLite baseline schema (GH #258, plan D10). GENERATED by
-- tools/db/gen_sqlite_baseline.py from a Postgres database with all
-- 71 templates/migrations/*.sql applied (001_init.sql .. 071_provider_key_agent_use.sql); hand-reviewed, then frozen.
-- Do not edit by hand: change the generator and regenerate.
--
-- 57 tables, 60 indexes, 3 triggers. Needs SQLite >= 3.38.
-- Every statement ends with ';' at end of line (run_migrations splits on it).

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);

CREATE TABLE containers (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    root_task_id UUID,
    max_auto_agents INTEGER NOT NULL DEFAULT 12,
    max_tasks INTEGER NOT NULL DEFAULT 200,
    execution_mode TEXT NOT NULL DEFAULT 'human',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    completed_at TIMESTAMPTZ,
    wakes_enabled BOOLEAN NOT NULL DEFAULT 1,
    llm_api_key_enc TEXT,
    llm_api_key_hint TEXT,
    llm_api_key_set_at TIMESTAMPTZ,
    autonomy_level TEXT NOT NULL DEFAULT 'plan',
    github_repo TEXT,
    last_wake_scan_at TIMESTAMPTZ,
    autonomy_enforced BOOLEAN NOT NULL DEFAULT 0,
    slack_webhook_url TEXT,
    worktrees_disabled BOOLEAN NOT NULL DEFAULT 0,
    icon JSONB,
    review_route TEXT NOT NULL DEFAULT 'manager_chain',
    ai_manager_prereview BOOLEAN NOT NULL DEFAULT 1,
    project_mode TEXT NOT NULL DEFAULT 'code',
    template_key TEXT,
    worktree_auto_cleanup BOOLEAN NOT NULL DEFAULT 1,
    worktree_grace_days INTEGER NOT NULL DEFAULT 7,
    CONSTRAINT containers_autonomy_level_check CHECK ((autonomy_level IN ('plan', 'pr', 'full'))),
    CONSTRAINT containers_project_mode_chk CHECK ((project_mode IN ('code', 'general'))),
    CONSTRAINT containers_review_route_check CHECK ((review_route IN ('manager_chain', 'owner', 'anyone')))
);

CREATE TABLE agent_worktree_inventory (
    container_id UUID PRIMARY KEY NOT NULL,
    host TEXT,
    base_cwd TEXT,
    items JSONB NOT NULL DEFAULT '[]',
    scanned_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_worktree_inventory_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE agents (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    alias TEXT NOT NULL,
    role TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'ai',
    system_prompt TEXT,
    status TEXT NOT NULL DEFAULT 'idle',
    is_auto_created BOOLEAN NOT NULL DEFAULT 0,
    parent_agent_id UUID,
    turn_budget INTEGER NOT NULL DEFAULT 50,
    turns_used INTEGER NOT NULL DEFAULT 0,
    last_heartbeat_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    terminated_at TIMESTAMPTZ,
    model TEXT,
    auto_wake_interval_secs INTEGER,
    reasoning_effort TEXT,
    github_login TEXT,
    member_role TEXT NOT NULL DEFAULT 'member',
    grants JSONB NOT NULL DEFAULT '[]',
    git_email TEXT,
    autonomy_override TEXT,
    slack_user_id TEXT,
    reports_to_agent_id UUID,
    CONSTRAINT agents_container_id_alias_key UNIQUE (container_id, alias),
    CONSTRAINT agents_auto_wake_interval_secs_check CHECK (((auto_wake_interval_secs IS NULL) OR (auto_wake_interval_secs >= 60))),
    CONSTRAINT agents_autonomy_override_check CHECK ((autonomy_override IN ('plan', 'pr', 'full'))),
    CONSTRAINT agents_kind_check CHECK ((kind IN ('ai', 'human'))),
    CONSTRAINT agents_member_role_check CHECK ((member_role IN ('owner', 'member', 'viewer'))),
    CONSTRAINT agents_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT agents_parent_agent_id_fkey FOREIGN KEY (parent_agent_id) REFERENCES agents(id),
    CONSTRAINT agents_reports_to_agent_id_fkey FOREIGN KEY (reports_to_agent_id) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE agent_budgets (
    agent_id UUID PRIMARY KEY NOT NULL,
    container_id UUID NOT NULL,
    monthly_limit_usd REAL,
    monthly_limit_tokens INTEGER,
    override_period TEXT,
    override_by UUID,
    override_at TIMESTAMPTZ,
    override_note TEXT,
    warned_period TEXT,
    paused_period TEXT,
    updated_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_budgets_monthly_limit_tokens_check CHECK (((monthly_limit_tokens IS NULL) OR (monthly_limit_tokens >= 0))),
    CONSTRAINT agent_budgets_monthly_limit_usd_check CHECK (((monthly_limit_usd IS NULL) OR (monthly_limit_usd >= (0)))),
    CONSTRAINT agent_budgets_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT agent_budgets_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT agent_budgets_override_by_fkey FOREIGN KEY (override_by) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT agent_budgets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE agent_config_revisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id UUID NOT NULL,
    container_id UUID NOT NULL,
    revision_no INTEGER NOT NULL,
    kind TEXT NOT NULL,
    source TEXT NOT NULL,
    snapshot JSONB NOT NULL,
    changes JSONB NOT NULL DEFAULT '[]',
    actor_agent_id UUID,
    actor_kind TEXT,
    actor_alias TEXT,
    restored_from INTEGER,
    reason TEXT,
    redacted_fields JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_config_revisions_agent_id_revision_no_key UNIQUE (agent_id, revision_no),
    CONSTRAINT agent_config_revisions_actor_kind_check CHECK (((actor_kind IS NULL) OR (actor_kind IN ('human', 'ai')))),
    CONSTRAINT agent_config_revisions_kind_check CHECK ((kind IN ('initial', 'change', 'restore'))),
    CONSTRAINT agent_config_revisions_revision_no_check CHECK ((revision_no >= 1)),
    CONSTRAINT agent_config_revisions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT agent_config_revisions_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE agent_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    container_id UUID,
    target_id UUID,
    event_key TEXT NOT NULL,
    event_name TEXT NOT NULL,
    ts REAL NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_events_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT agent_events_target_id_fkey FOREIGN KEY (target_id) REFERENCES agents(id)
);

CREATE TABLE agent_event_acks (
    agent_id UUID NOT NULL,
    event_id INTEGER NOT NULL,
    handled_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    PRIMARY KEY (agent_id, event_id),
    CONSTRAINT agent_event_acks_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT agent_event_acks_event_id_fkey FOREIGN KEY (event_id) REFERENCES agent_events(id) ON DELETE CASCADE
);

CREATE TABLE agent_memory_digests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    container_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    snapshot_ts REAL NOT NULL,
    current_focus TEXT,
    decisions JSONB NOT NULL DEFAULT '[]',
    learnings JSONB NOT NULL DEFAULT '[]',
    open_threads JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    audience TEXT,
    CONSTRAINT agent_memory_digests_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT agent_memory_digests_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id)
);

CREATE TABLE agent_notification_state (
    agent_id UUID PRIMARY KEY NOT NULL,
    read_through_ts REAL NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_notification_state_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE TABLE agent_reachability (
    agent_id UUID PRIMARY KEY NOT NULL,
    wake_enabled BOOLEAN NOT NULL DEFAULT 1,
    tmux_target TEXT,
    headless_cwd TEXT,
    headless_flags TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_reachability_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id)
);

CREATE TABLE agent_wake_state (
    agent_id UUID PRIMARY KEY NOT NULL,
    delivered_ts REAL NOT NULL DEFAULT 0,
    last_woken_at TIMESTAMPTZ,
    last_wake_kind TEXT,
    last_wake_event TEXT,
    wake_lease_until TIMESTAMPTZ,
    lease_kind TEXT,
    preempt_requested_at TIMESTAMPTZ,
    preempt_for TEXT,
    conv_lease_until TIMESTAMPTZ,
    conv_lease_kind TEXT,
    conv_preempt_requested_at TIMESTAMPTZ,
    conv_preempt_for TEXT,
    conv_delivered_ts REAL,
    conv_last_woken_at TIMESTAMPTZ,
    work_last_heartbeat_at TIMESTAMPTZ,
    conv_last_heartbeat_at TIMESTAMPTZ,
    CONSTRAINT agent_wake_state_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id)
);

CREATE TABLE agent_worktree_actions (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    action TEXT NOT NULL,
    path TEXT,
    branch TEXT,
    keep_branch BOOLEAN NOT NULL DEFAULT 0,
    confirm_unmerged BOOLEAN NOT NULL DEFAULT 0,
    include_output BOOLEAN NOT NULL DEFAULT 1,
    unmerged_paths JSONB NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'requested',
    requested_by UUID,
    claimed_by TEXT,
    result JSONB,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    claimed_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT agent_worktree_actions_action_check CHECK ((action IN ('remove', 'save_output', 'clean_up', 'refresh'))),
    CONSTRAINT agent_worktree_actions_status_check CHECK ((status IN ('requested', 'claimed', 'done', 'failed'))),
    CONSTRAINT agent_worktree_actions_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT agent_worktree_actions_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE container_budgets (
    container_id UUID PRIMARY KEY NOT NULL,
    monthly_limit_usd REAL,
    monthly_limit_tokens INTEGER,
    override_period TEXT,
    override_by UUID,
    override_at TIMESTAMPTZ,
    override_note TEXT,
    warned_period TEXT,
    paused_period TEXT,
    updated_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT container_budgets_monthly_limit_tokens_check CHECK (((monthly_limit_tokens IS NULL) OR (monthly_limit_tokens >= 0))),
    CONSTRAINT container_budgets_monthly_limit_usd_check CHECK (((monthly_limit_usd IS NULL) OR (monthly_limit_usd >= (0)))),
    CONSTRAINT container_budgets_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT container_budgets_override_by_fkey FOREIGN KEY (override_by) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT container_budgets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE container_github_pat (
    container_id UUID PRIMARY KEY NOT NULL,
    token_enc TEXT NOT NULL,
    token_hint TEXT,
    set_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT container_github_pat_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE container_model_settings (
    container_id UUID NOT NULL,
    use_case_key TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    set_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    PRIMARY KEY (container_id, use_case_key),
    CONSTRAINT container_model_settings_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE container_provider_keys (
    container_id UUID NOT NULL,
    provider TEXT NOT NULL,
    key_enc TEXT NOT NULL,
    key_hint TEXT,
    set_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    use_for_agents BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (container_id, provider),
    CONSTRAINT container_provider_keys_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE container_verdikt_settings (
    container_id UUID PRIMARY KEY NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT 0,
    base_url TEXT,
    verdikt_project TEXT,
    target_kind TEXT NOT NULL DEFAULT 'web',
    target_locator TEXT,
    trigger_mode TEXT NOT NULL DEFAULT 'manual',
    timeout_minutes INTEGER NOT NULL DEFAULT 30,
    updated_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    preview_command TEXT,
    preview_ready_path TEXT NOT NULL DEFAULT '/',
    preview_timeout_seconds INTEGER NOT NULL DEFAULT 120,
    preview_ttl_minutes INTEGER NOT NULL DEFAULT 60,
    autofix_enabled BOOLEAN NOT NULL DEFAULT 0,
    autofix_max_attempts INTEGER NOT NULL DEFAULT 3,
    CONSTRAINT container_verdikt_settings_autofix_max_chk CHECK (((autofix_max_attempts >= 1) AND (autofix_max_attempts <= 10))),
    CONSTRAINT container_verdikt_settings_target_kind_check CHECK ((target_kind IN ('web', 'ios', 'android'))),
    CONSTRAINT container_verdikt_settings_timeout_minutes_check CHECK (((timeout_minutes >= 1) AND (timeout_minutes <= 240))),
    CONSTRAINT container_verdikt_settings_trigger_mode_check CHECK ((trigger_mode IN ('manual', 'ui_changes', 'always'))),
    CONSTRAINT container_verdikt_settings_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT container_verdikt_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE conversations (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    started_by UUID NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    session_id UUID,
    title TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    last_turn_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    session_pinned_at TIMESTAMPTZ,
    CONSTRAINT conversations_status_check CHECK ((status IN ('active', 'idle', 'ended'))),
    CONSTRAINT conversations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT conversations_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT conversations_started_by_fkey FOREIGN KEY (started_by) REFERENCES agents(id)
);

CREATE TABLE decisions (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    decision TEXT NOT NULL,
    reason TEXT,
    actor_agent_id UUID NOT NULL,
    target_agent_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT decisions_decision_check CHECK ((decision IN ('approve', 'reject'))),
    CONSTRAINT decisions_reject_needs_reason CHECK (((decision <> 'reject') OR ((reason IS NOT NULL) AND (length(trim(reason)) > 0)))),
    CONSTRAINT decisions_actor_agent_id_fkey FOREIGN KEY (actor_agent_id) REFERENCES agents(id),
    CONSTRAINT decisions_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT decisions_target_agent_id_fkey FOREIGN KEY (target_agent_id) REFERENCES agents(id)
);

CREATE TABLE device_tokens (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    token_hash TEXT NOT NULL,
    label TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT device_tokens_token_hash_key UNIQUE (token_hash),
    CONSTRAINT device_tokens_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT device_tokens_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id)
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    container_id UUID NOT NULL,
    actor_type TEXT NOT NULL,
    actor_id UUID,
    entity_type TEXT NOT NULL,
    entity_id UUID,
    event_type TEXT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT events_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id)
);

CREATE TABLE notification_pref_defaults (
    identity_key TEXT PRIMARY KEY NOT NULL,
    prefs JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);

CREATE TABLE notification_prefs (
    member_agent_id UUID PRIMARY KEY NOT NULL,
    container_id UUID NOT NULL,
    prefs JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT notification_prefs_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT notification_prefs_member_agent_id_fkey FOREIGN KEY (member_agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE TABLE plan_usage_display (
    id INTEGER PRIMARY KEY NOT NULL DEFAULT 1,
    show BOOLEAN NOT NULL DEFAULT 0,
    providers TEXT NOT NULL DEFAULT 'both',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT plan_usage_display_id_check CHECK ((id = 1)),
    CONSTRAINT plan_usage_display_providers_check CHECK ((providers IN ('both', 'claude', 'codex')))
);

CREATE TABLE plan_usage_snapshots (
    host TEXT PRIMARY KEY NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}',
    captured_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);

CREATE TABLE project_dod_presets (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    name TEXT NOT NULL,
    body TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    created_by_agent_id UUID,
    updated_by_agent_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    archived_at TIMESTAMPTZ,
    CONSTRAINT project_dod_presets_body_check CHECK (((length(trim(body)) >= 1) AND (length(trim(body)) <= 4000))),
    CONSTRAINT project_dod_presets_name_check CHECK (((length(trim(name)) >= 1) AND (length(trim(name)) <= 120))),
    CONSTRAINT project_dod_presets_source_check CHECK ((source IN ('manual', 'template_import'))),
    CONSTRAINT project_dod_presets_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT project_dod_presets_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT project_dod_presets_updated_by_agent_id_fkey FOREIGN KEY (updated_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE project_skills (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    body TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    created_by_agent_id UUID,
    updated_by_agent_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    archived_at TIMESTAMPTZ,
    CONSTRAINT project_skills_body_check CHECK (((length(trim(body)) >= 1) AND (length(trim(body)) <= 20000))),
    CONSTRAINT project_skills_description_check CHECK (((description IS NULL) OR (length(description) <= 300))),
    CONSTRAINT project_skills_name_check CHECK (length(name) BETWEEN 1 AND 63 AND name GLOB '[a-z0-9]*' AND name NOT GLOB '*[^a-z0-9-]*'),
    CONSTRAINT project_skills_source_check CHECK ((source IN ('manual', 'template_import'))),
    CONSTRAINT project_skills_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT project_skills_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT project_skills_updated_by_agent_id_fkey FOREIGN KEY (updated_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE project_template_applications (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    template_key TEXT NOT NULL,
    template_version INTEGER NOT NULL,
    applied_by_agent_id UUID,
    plan JSONB NOT NULL,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT project_template_applications_applied_by_agent_id_fkey FOREIGN KEY (applied_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT project_template_applications_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id)
);

CREATE TABLE push_devices (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    github_login TEXT NOT NULL,
    apns_token TEXT NOT NULL,
    platform TEXT NOT NULL DEFAULT 'ios',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    last_seen_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT push_devices_apns_token_key UNIQUE (apns_token)
);

CREATE TABLE push_outbox (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    container_id UUID NOT NULL,
    kind TEXT NOT NULL,
    ref_id UUID NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    delivered_at TIMESTAMPTZ,
    failed TEXT,
    CONSTRAINT push_outbox_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE roster_analysis (
    container_id UUID PRIMARY KEY NOT NULL,
    summary TEXT NOT NULL,
    suggestions JSONB NOT NULL,
    source TEXT NOT NULL,
    model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT roster_analysis_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE routine_scheduler_state (
    container_id UUID PRIMARY KEY NOT NULL,
    last_tick_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT routine_scheduler_state_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id)
);

CREATE TABLE tasks (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    definition_of_done TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    priority INTEGER NOT NULL DEFAULT 100,
    is_root BOOLEAN NOT NULL DEFAULT 0,
    created_by_agent_id UUID,
    result JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    protocol JSONB,
    reviewer_agent_id UUID,
    review_routing JSONB,
    manager_review JSONB,
    parent_task_id UUID,
    CONSTRAINT tasks_parent_not_self CHECK (((parent_task_id IS NULL) OR (parent_task_id <> id))),
    CONSTRAINT tasks_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT tasks_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES agents(id),
    CONSTRAINT tasks_parent_task_id_fkey FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT tasks_reviewer_agent_id_fkey FOREIGN KEY (reviewer_agent_id) REFERENCES agents(id)
);

CREATE TABLE agent_self_wake (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    agent_id UUID NOT NULL,
    task_id UUID NOT NULL,
    resume_at TIMESTAMPTZ NOT NULL,
    context TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT agent_self_wake_agent_id_task_id_key UNIQUE (agent_id, task_id),
    CONSTRAINT agent_self_wake_context_nonempty CHECK ((trim(context) <> '')),
    CONSTRAINT agent_self_wake_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT agent_self_wake_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE agent_tasks (
    agent_id UUID NOT NULL,
    task_id UUID NOT NULL,
    assignment_status TEXT NOT NULL DEFAULT 'assigned',
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    PRIMARY KEY (agent_id, task_id),
    CONSTRAINT agent_tasks_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT agent_tasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE requests (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    type TEXT NOT NULL,
    requester_id UUID NOT NULL,
    target_id UUID,
    priority INTEGER NOT NULL DEFAULT 100,
    status TEXT NOT NULL DEFAULT 'open',
    payload TEXT NOT NULL,
    response TEXT,
    rejection_reason TEXT,
    spawned_task_id UUID,
    expires_at TIMESTAMPTZ,
    parent_request_id UUID,
    chain_depth INTEGER NOT NULL DEFAULT 0,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    responded_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    originating_task_id UUID,
    agent_payload TEXT,
    CONSTRAINT requests_check CHECK ((id <> parent_request_id)),
    CONSTRAINT requests_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT requests_originating_task_id_fkey FOREIGN KEY (originating_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT requests_parent_request_id_fkey FOREIGN KEY (parent_request_id) REFERENCES requests(id),
    CONSTRAINT requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES agents(id),
    CONSTRAINT requests_spawned_task_id_fkey FOREIGN KEY (spawned_task_id) REFERENCES tasks(id),
    CONSTRAINT requests_target_id_fkey FOREIGN KEY (target_id) REFERENCES agents(id)
);

CREATE TABLE code_threads (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    repo TEXT NOT NULL,
    ref TEXT NOT NULL,
    sha TEXT NOT NULL,
    path TEXT NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    kind TEXT NOT NULL DEFAULT 'note',
    status TEXT NOT NULL DEFAULT 'open',
    created_by_agent_id UUID NOT NULL,
    tagged_agent_id UUID,
    request_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT code_threads_check CHECK ((end_line >= start_line)),
    CONSTRAINT code_threads_kind_check CHECK ((kind IN ('question', 'why', 'teach', 'note'))),
    CONSTRAINT code_threads_status_check CHECK ((status IN ('open', 'answered', 'resolved'))),
    CONSTRAINT code_threads_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT code_threads_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES agents(id),
    CONSTRAINT code_threads_request_id_fkey FOREIGN KEY (request_id) REFERENCES requests(id),
    CONSTRAINT code_threads_tagged_agent_id_fkey FOREIGN KEY (tagged_agent_id) REFERENCES agents(id)
);

CREATE TABLE code_thread_messages (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    thread_id UUID NOT NULL,
    author_agent_id UUID,
    is_human BOOLEAN NOT NULL DEFAULT 0,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT code_thread_messages_author_agent_id_fkey FOREIGN KEY (author_agent_id) REFERENCES agents(id),
    CONSTRAINT code_thread_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES code_threads(id)
);

CREATE TABLE routines (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    definition_of_done TEXT NOT NULL,
    assignee_agent_id UUID,
    priority INTEGER NOT NULL DEFAULT 100,
    cron TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    enabled BOOLEAN NOT NULL DEFAULT 1,
    skip_if_open BOOLEAN NOT NULL DEFAULT 1,
    next_run_at TIMESTAMPTZ,
    last_run_at TIMESTAMPTZ,
    created_by_agent_id UUID,
    updated_by_agent_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    archived_at TIMESTAMPTZ,
    origin_task_id UUID,
    CONSTRAINT routines_assignee_agent_id_fkey FOREIGN KEY (assignee_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT routines_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT routines_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT routines_origin_task_id_fkey FOREIGN KEY (origin_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT routines_updated_by_agent_id_fkey FOREIGN KEY (updated_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE routine_runs (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    routine_id UUID NOT NULL,
    container_id UUID NOT NULL,
    trigger TEXT NOT NULL,
    scheduled_for TIMESTAMPTZ,
    missed_count INTEGER NOT NULL DEFAULT 0,
    outcome TEXT NOT NULL,
    task_id UUID,
    detail TEXT,
    actor_agent_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    finished_at TIMESTAMPTZ,
    CONSTRAINT routine_runs_outcome_check CHECK ((outcome IN ('pending', 'created', 'skipped', 'failed'))),
    CONSTRAINT routine_runs_trigger_check CHECK ((trigger IN ('schedule', 'catch_up', 'manual'))),
    CONSTRAINT routine_runs_actor_agent_id_fkey FOREIGN KEY (actor_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT routine_runs_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id),
    CONSTRAINT routine_runs_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES routines(id),
    CONSTRAINT routine_runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);

CREATE TABLE task_deliverables (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    container_id UUID NOT NULL,
    task_id UUID NOT NULL,
    path TEXT NOT NULL,
    kind TEXT NOT NULL,
    latest_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT task_deliverables_task_id_path_key UNIQUE (task_id, path),
    CONSTRAINT task_deliverables_path_check CHECK (((length(path) >= 1) AND (length(path) <= 255))),
    CONSTRAINT task_deliverables_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT task_deliverables_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE task_dependencies (
    task_id UUID NOT NULL,
    depends_on_id UUID NOT NULL,
    PRIMARY KEY (task_id, depends_on_id),
    CONSTRAINT task_dependencies_check CHECK ((task_id <> depends_on_id)),
    CONSTRAINT task_dependencies_depends_on_id_fkey FOREIGN KEY (depends_on_id) REFERENCES tasks(id),
    CONSTRAINT task_dependencies_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE task_evidence_packs (
    task_id UUID PRIMARY KEY NOT NULL,
    container_id UUID NOT NULL,
    basis TEXT NOT NULL,
    pack JSONB NOT NULL,
    built_reason TEXT NOT NULL DEFAULT 'read',
    built_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT task_evidence_packs_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT task_evidence_packs_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE task_messages (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    task_id UUID NOT NULL,
    author_id UUID,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    attachments JSONB NOT NULL DEFAULT '[]',
    CONSTRAINT task_messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES agents(id),
    CONSTRAINT task_messages_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE user_prefs (
    github_login TEXT PRIMARY KEY NOT NULL,
    prefs JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);

CREATE TABLE verdikt_autofix_loops (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    task_id UUID NOT NULL,
    container_id UUID NOT NULL,
    status TEXT NOT NULL,
    max_attempts INTEGER NOT NULL,
    stop_kind TEXT,
    stop_reason TEXT,
    stopped_by UUID,
    started_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    stopped_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT verdikt_autofix_loops_max_attempts_check CHECK (((max_attempts >= 1) AND (max_attempts <= 10))),
    CONSTRAINT verdikt_autofix_loops_status_check CHECK ((status IN ('running', 'stopped'))),
    CONSTRAINT verdikt_autofix_loops_stop_kind_check CHECK (((stop_kind IS NULL) OR (stop_kind IN ('pass', 'attempt_limit', 'no_diff', 'same_failure', 'non_fail', 'budget', 'agent_paused', 'human', 'stopped_by_human', 'turned_off', 'no_assignee')))),
    CONSTRAINT verdikt_autofix_loops_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_autofix_loops_stopped_by_fkey FOREIGN KEY (stopped_by) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT verdikt_autofix_loops_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE verdikt_runs (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    task_id UUID NOT NULL,
    container_id UUID NOT NULL,
    trigger TEXT NOT NULL,
    triggered_by UUID,
    status TEXT NOT NULL,
    verdict TEXT,
    base_url TEXT NOT NULL,
    verdikt_project_id TEXT,
    verdikt_scenario_id TEXT,
    verdikt_request_id TEXT,
    verdikt_run_id TEXT,
    target_kind TEXT NOT NULL,
    locator TEXT NOT NULL,
    handoff JSONB NOT NULL DEFAULT '{}',
    criteria JSONB NOT NULL DEFAULT '[]',
    screenshots JSONB NOT NULL DEFAULT '[]',
    reason TEXT,
    report_url TEXT,
    video_url TEXT,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    last_polled_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    autofix BOOLEAN NOT NULL DEFAULT 0,
    autofix_done_at TIMESTAMPTZ,
    CONSTRAINT verdikt_runs_status_check CHECK ((status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'timeout', 'unavailable'))),
    CONSTRAINT verdikt_runs_trigger_check CHECK ((trigger IN ('manual', 'auto'))),
    CONSTRAINT verdikt_runs_verdict_check CHECK (((verdict IS NULL) OR (verdict IN ('pass', 'fail', 'blocked', 'warning', 'unprocessable', 'running')))),
    CONSTRAINT verdikt_runs_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_runs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE verdikt_autofix_attempts (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    loop_id UUID NOT NULL,
    task_id UUID NOT NULL,
    attempt INTEGER NOT NULL,
    verdikt_run_id UUID NOT NULL,
    outcome TEXT NOT NULL,
    action TEXT NOT NULL,
    failure_signature TEXT,
    change_signature TEXT,
    failed JSONB NOT NULL DEFAULT '[]',
    changes JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT verdikt_autofix_attempts_verdikt_run_id_key UNIQUE (verdikt_run_id),
    CONSTRAINT verdikt_autofix_attempts_action_check CHECK ((action IN ('reworked', 'stopped', 'passed'))),
    CONSTRAINT verdikt_autofix_attempts_attempt_check CHECK ((attempt >= 1)),
    CONSTRAINT verdikt_autofix_attempts_loop_id_fkey FOREIGN KEY (loop_id) REFERENCES verdikt_autofix_loops(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_autofix_attempts_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_autofix_attempts_verdikt_run_id_fkey FOREIGN KEY (verdikt_run_id) REFERENCES verdikt_runs(id) ON DELETE CASCADE
);

CREATE TABLE verdikt_previews (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    task_id UUID NOT NULL,
    container_id UUID NOT NULL,
    verdikt_run_id UUID,
    status TEXT NOT NULL,
    command TEXT NOT NULL,
    ready_path TEXT NOT NULL DEFAULT '/',
    timeout_seconds INTEGER NOT NULL DEFAULT 120,
    ttl_minutes INTEGER NOT NULL DEFAULT 60,
    worktree TEXT,
    branch TEXT,
    base_cwd TEXT,
    port INTEGER,
    verdikt_url TEXT,
    error TEXT,
    log_tail TEXT,
    claimed_by TEXT,
    stop_reason TEXT,
    stop_requested_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    claimed_at TIMESTAMPTZ,
    ready_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    stopped_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT verdikt_previews_port_check CHECK (((port IS NULL) OR ((port >= 1024) AND (port <= 65535)))),
    CONSTRAINT verdikt_previews_status_check CHECK ((status IN ('requested', 'starting', 'ready', 'failed', 'stopped'))),
    CONSTRAINT verdikt_previews_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_previews_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_previews_verdikt_run_id_fkey FOREIGN KEY (verdikt_run_id) REFERENCES verdikt_runs(id) ON DELETE CASCADE
);

CREATE TABLE verdikt_task_autofix (
    task_id UUID PRIMARY KEY NOT NULL,
    container_id UUID NOT NULL,
    mode TEXT NOT NULL,
    updated_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT verdikt_task_autofix_mode_check CHECK ((mode IN ('on', 'off'))),
    CONSTRAINT verdikt_task_autofix_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_task_autofix_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT verdikt_task_autofix_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE wake_backoff (
    container_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    wake_key TEXT NOT NULL,
    strikes INTEGER NOT NULL DEFAULT 0,
    suppressed_until TIMESTAMPTZ,
    last_strike_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    first_strike_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    notified_at TIMESTAMPTZ,
    PRIMARY KEY (agent_id, wake_key),
    CONSTRAINT wake_backoff_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT wake_backoff_container_id_fkey FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE
);

CREATE TABLE worker_runs (
    run_id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    agent_id UUID NOT NULL,
    task_id UUID,
    wake_kind TEXT,
    wake_event TEXT,
    status TEXT NOT NULL DEFAULT 'running',
    exit_code INTEGER,
    log_path TEXT,
    output TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    ended_at TIMESTAMPTZ,
    diff TEXT,
    pid INTEGER,
    runtime TEXT,
    conversation_id UUID,
    conversation_ack_ts REAL,
    last_message_path TEXT,
    worktree TEXT,
    branch TEXT,
    base_cwd TEXT,
    kill_reason TEXT,
    stop_requested_at TIMESTAMPTZ,
    stop_requested_by TEXT,
    input_tokens INTEGER,
    output_tokens INTEGER,
    cache_read_input_tokens INTEGER,
    cache_creation_input_tokens INTEGER,
    total_cost_usd REAL,
    lane TEXT NOT NULL DEFAULT 'work',
    sandbox_container_id TEXT,
    CONSTRAINT worker_runs_lane_chk CHECK ((lane IN ('work', 'conversation'))),
    CONSTRAINT worker_runs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT worker_runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
    CONSTRAINT worker_runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);

CREATE TABLE conversation_turns (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    conversation_id UUID NOT NULL,
    seq INTEGER NOT NULL,
    role TEXT NOT NULL,
    author_agent_id UUID NOT NULL,
    content TEXT NOT NULL,
    run_id UUID,
    meta JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    attachments JSONB NOT NULL DEFAULT '[]',
    CONSTRAINT conversation_turns_conversation_id_seq_key UNIQUE (conversation_id, seq),
    CONSTRAINT conversation_turns_role_check CHECK ((role IN ('human', 'agent'))),
    CONSTRAINT conversation_turns_author_agent_id_fkey FOREIGN KEY (author_agent_id) REFERENCES agents(id),
    CONSTRAINT conversation_turns_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT conversation_turns_run_id_fkey FOREIGN KEY (run_id) REFERENCES worker_runs(run_id) ON DELETE SET NULL
);

CREATE TABLE embodiment_tokens (
    run_token TEXT PRIMARY KEY NOT NULL,
    agent_id UUID NOT NULL,
    lane TEXT NOT NULL,
    kind TEXT NOT NULL,
    run_id UUID,
    pid INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    revoked_at TIMESTAMPTZ,
    CONSTRAINT embodiment_tokens_lane_check CHECK ((lane IN ('work', 'conversation'))),
    CONSTRAINT embodiment_tokens_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT embodiment_tokens_run_id_fkey FOREIGN KEY (run_id) REFERENCES worker_runs(run_id) ON DELETE CASCADE
);

CREATE TABLE task_deliverable_versions (
    id UUID PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    deliverable_id UUID NOT NULL,
    version INTEGER NOT NULL,
    source TEXT NOT NULL,
    run_id UUID,
    author_agent_id UUID,
    stored_name TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    sha256 TEXT NOT NULL,
    content_type TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    CONSTRAINT task_deliverable_versions_deliverable_id_version_key UNIQUE (deliverable_id, version),
    CONSTRAINT task_deliverable_versions_size_bytes_check CHECK ((size_bytes >= 0)),
    CONSTRAINT task_deliverable_versions_source_check CHECK ((source IN ('run_output', 'attached'))),
    CONSTRAINT task_deliverable_versions_version_check CHECK ((version >= 1)),
    CONSTRAINT task_deliverable_versions_author_agent_id_fkey FOREIGN KEY (author_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT task_deliverable_versions_deliverable_id_fkey FOREIGN KEY (deliverable_id) REFERENCES task_deliverables(id) ON DELETE CASCADE,
    CONSTRAINT task_deliverable_versions_run_id_fkey FOREIGN KEY (run_id) REFERENCES worker_runs(run_id) ON DELETE SET NULL
);

CREATE TABLE worker_run_lines (
    run_id UUID NOT NULL,
    seq INTEGER NOT NULL,
    line TEXT NOT NULL,
    ts TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    PRIMARY KEY (run_id, seq),
    CONSTRAINT worker_run_lines_run_id_fkey FOREIGN KEY (run_id) REFERENCES worker_runs(run_id) ON DELETE CASCADE
);

CREATE TABLE worker_run_tasks (
    run_id UUID NOT NULL,
    task_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
    PRIMARY KEY (run_id, task_id),
    CONSTRAINT worker_run_tasks_run_id_fkey FOREIGN KEY (run_id) REFERENCES worker_runs(run_id) ON DELETE CASCADE,
    CONSTRAINT worker_run_tasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE INDEX idx_agent_budgets_container ON agent_budgets (container_id);
CREATE INDEX agent_config_revisions_agent_idx ON agent_config_revisions (agent_id, revision_no DESC);
CREATE INDEX idx_agent_event_acks_event ON agent_event_acks (event_id);
CREATE INDEX idx_agent_events_key_ts ON agent_events (event_key, ts, id);
CREATE INDEX idx_digest_agent_ts ON agent_memory_digests (agent_id, snapshot_ts DESC);
CREATE INDEX idx_agent_self_wake_due ON agent_self_wake (resume_at);
CREATE INDEX idx_agent_tasks_agent ON agent_tasks (agent_id, assignment_status);
CREATE INDEX idx_agent_worktree_actions_open ON agent_worktree_actions (container_id, created_at) WHERE status IN ('requested', 'claimed');
CREATE INDEX idx_agent_worktree_actions_recent ON agent_worktree_actions (container_id, created_at DESC);
CREATE UNIQUE INDEX agents_container_github_login_uq ON agents (container_id, lower(github_login)) WHERE github_login IS NOT NULL;
CREATE UNIQUE INDEX agents_container_slack_user_uq ON agents (container_id, slack_user_id) WHERE slack_user_id IS NOT NULL;
CREATE INDEX agents_reports_to_idx ON agents (reports_to_agent_id) WHERE reports_to_agent_id IS NOT NULL;
CREATE INDEX idx_agents_container_kind ON agents (container_id, kind);
CREATE INDEX code_thread_messages_thread_id_idx ON code_thread_messages (thread_id, created_at);
CREATE INDEX code_threads_container_ref_path_idx ON code_threads (container_id, ref, path);
CREATE INDEX code_threads_container_status_idx ON code_threads (container_id, status);
CREATE INDEX code_threads_request_id_idx ON code_threads (request_id) WHERE request_id IS NOT NULL;
CREATE UNIQUE INDEX containers_name_uq ON containers (lower(name));
CREATE INDEX idx_turns_conversation_seq ON conversation_turns (conversation_id, seq);
CREATE UNIQUE INDEX idx_conversations_one_active ON conversations (agent_id) WHERE status = 'active';
CREATE INDEX idx_decisions_subject ON decisions (subject_type, subject_id);
CREATE INDEX idx_decisions_target ON decisions (target_agent_id);
CREATE INDEX device_tokens_agent_idx ON device_tokens (agent_id);
CREATE INDEX embodiment_tokens_agent_live ON embodiment_tokens (agent_id) WHERE revoked_at IS NULL;
CREATE INDEX embodiment_tokens_run_live ON embodiment_tokens (run_id) WHERE revoked_at IS NULL;
CREATE INDEX idx_events_request_entity ON events (entity_id, event_type, created_at) WHERE entity_type = 'request';
CREATE INDEX notification_prefs_container_idx ON notification_prefs (container_id);
CREATE INDEX idx_plan_usage_snapshots_updated ON plan_usage_snapshots (updated_at DESC);
CREATE UNIQUE INDEX uq_project_dod_presets_name ON project_dod_presets (container_id, lower(name)) WHERE archived_at IS NULL;
CREATE UNIQUE INDEX uq_project_skills_name ON project_skills (container_id, name) WHERE archived_at IS NULL;
CREATE INDEX idx_template_applications_container ON project_template_applications (container_id, created_at DESC);
CREATE INDEX push_devices_login_idx ON push_devices (github_login);
CREATE INDEX push_outbox_pending_idx ON push_outbox (created_at) WHERE (delivered_at IS NULL) AND (failed IS NULL);
CREATE INDEX idx_requests_parent ON requests (parent_request_id);
CREATE INDEX idx_requests_requester ON requests (requester_id, status);
CREATE INDEX idx_requests_target_open ON requests (target_id, status, priority);
CREATE INDEX idx_routine_runs_routine ON routine_runs (routine_id, created_at DESC);
CREATE UNIQUE INDEX uq_routine_runs_slot ON routine_runs (routine_id, scheduled_for) WHERE scheduled_for IS NOT NULL;
CREATE INDEX idx_routines_container ON routines (container_id) WHERE archived_at IS NULL;
CREATE INDEX idx_routines_due ON routines (next_run_at) WHERE enabled AND (archived_at IS NULL);
CREATE INDEX idx_routines_origin_task ON routines (origin_task_id) WHERE (origin_task_id IS NOT NULL) AND (archived_at IS NULL);
CREATE INDEX idx_task_deliverable_versions_run ON task_deliverable_versions (run_id) WHERE run_id IS NOT NULL;
CREATE INDEX idx_task_deliverables_task ON task_deliverables (task_id, updated_at DESC);
CREATE INDEX idx_task_evidence_packs_container ON task_evidence_packs (container_id);
CREATE INDEX idx_tasks_container_status ON tasks (container_id, status, priority);
CREATE INDEX idx_tasks_parent_task ON tasks (parent_task_id) WHERE parent_task_id IS NOT NULL;
CREATE INDEX idx_verdikt_autofix_attempts_loop ON verdikt_autofix_attempts (loop_id, attempt);
CREATE INDEX idx_verdikt_autofix_loops_task ON verdikt_autofix_loops (task_id, started_at DESC);
CREATE UNIQUE INDEX uq_verdikt_autofix_loops_running ON verdikt_autofix_loops (task_id) WHERE status = 'running';
CREATE INDEX idx_verdikt_previews_open ON verdikt_previews (container_id, status) WHERE status IN ('requested', 'starting', 'ready');
CREATE INDEX idx_verdikt_previews_run ON verdikt_previews (verdikt_run_id);
CREATE INDEX idx_verdikt_runs_autofix_pending ON verdikt_runs (task_id) WHERE autofix AND (autofix_done_at IS NULL);
CREATE INDEX idx_verdikt_runs_open ON verdikt_runs (status) WHERE status IN ('queued', 'running');
CREATE INDEX idx_verdikt_runs_task ON verdikt_runs (task_id, created_at DESC);
CREATE INDEX idx_wake_backoff_container ON wake_backoff (container_id);
CREATE INDEX worker_run_tasks_task ON worker_run_tasks (task_id);
CREATE INDEX idx_worker_runs_agent_started ON worker_runs (agent_id, started_at DESC);
CREATE INDEX idx_worker_runs_running_conversation ON worker_runs (agent_id, status, runtime, conversation_id, started_at DESC) WHERE conversation_id IS NOT NULL;
CREATE INDEX idx_worker_runs_sandbox_live ON worker_runs (sandbox_container_id) WHERE status = 'running';
CREATE INDEX idx_worker_runs_task ON worker_runs (task_id);

CREATE TRIGGER agent_config_revisions_no_update BEFORE UPDATE ON agent_config_revisions BEGIN SELECT RAISE(ABORT, 'agent_config_revisions rows are immutable (history is append-only)'); END;
CREATE TRIGGER worker_run_task_sync_ins AFTER INSERT ON worker_runs WHEN NEW.task_id IS NOT NULL BEGIN INSERT OR IGNORE INTO worker_run_tasks (run_id, task_id) VALUES (NEW.run_id, NEW.task_id); END;
CREATE TRIGGER worker_run_task_sync_upd AFTER UPDATE OF task_id ON worker_runs WHEN NEW.task_id IS NOT NULL BEGIN INSERT OR IGNORE INTO worker_run_tasks (run_id, task_id) VALUES (NEW.run_id, NEW.task_id); END;

-- The baseline's own row plus every Postgres migration it folds in, so a fresh
-- SQLite DB and one converted from Postgres report the same history and tip.
INSERT OR IGNORE INTO schema_migrations (version) VALUES
    ('001_baseline.sql'),
    ('001_init.sql'),
    ('002_wake_single_flight.sql'),
    ('003_decisions.sql'),
    ('004_worker_runs.sql'),
    ('005_worker_run_diff.sql'),
    ('006_worker_run_lines.sql'),
    ('007_agent_model.sql'),
    ('008_conversations.sql'),
    ('009_embodiment_lease.sql'),
    ('010_wake_kind_ephemeral.sql'),
    ('011_preempt_yield.sql'),
    ('012_resident_cold_resync.sql'),
    ('013_worker_run_pid.sql'),
    ('014_codex_worker_run_metadata.sql'),
    ('015_task_protocol.sql'),
    ('016_worker_run_kill_reason.sql'),
    ('017_worker_run_stop.sql'),
    ('018_agent_auto_wake.sql'),
    ('019_worker_run_tokens.sql'),
    ('020_container_llm_key.sql'),
    ('021_container_autonomy_level.sql'),
    ('022_container_model_settings.sql'),
    ('023_agent_notification_state.sql'),
    ('024_digest_audience.sql'),
    ('025_task_message_attachments.sql'),
    ('026_conversation_turn_attachments.sql'),
    ('027_container_provider_keys.sql'),
    ('028_request_originating_task.sql'),
    ('030_conversation_lane.sql'),
    ('031_worker_run_tasks.sql'),
    ('032_agent_reasoning_effort.sql'),
    ('032_agent_self_wake.sql'),
    ('033_agent_event_acks.sql'),
    ('034_sandbox_runs.sql'),
    ('035_container_github_repo.sql'),
    ('036_collab.sql'),
    ('037_multi_project.sql'),
    ('038_device_tokens.sql'),
    ('039_access_model.sql'),
    ('040_user_prefs.sql'),
    ('041_push.sql'),
    ('042_human_git_identity.sql'),
    ('043_agent_autonomy_override.sql'),
    ('044_slack_integration.sql'),
    ('045_code_space.sql'),
    ('046_github_pat.sql'),
    ('047_roster_analysis.sql'),
    ('048_wake_backoff.sql'),
    ('049_disable_worktrees.sql'),
    ('050_container_icon.sql'),
    ('051_request_event_index.sql'),
    ('052_agent_reports_to.sql'),
    ('053_budgets.sql'),
    ('054_routines.sql'),
    ('055_agent_config_revisions.sql'),
    ('056_max_auto_agents_default.sql'),
    ('057_manager_review_handoff.sql'),
    ('058_evidence_verdikt.sql'),
    ('059_portable_templates.sql'),
    ('060_general_mode_templates.sql'),
    ('061_task_deliverables.sql'),
    ('062_goal_ancestry.sql'),
    ('063_notification_prefs.sql'),
    ('064_verdikt_previews.sql'),
    ('065_request_agent_payload.sql'),
    ('066_routine_origin_task.sql'),
    ('067_agent_worktree_cleanup.sql'),
    ('068_verdikt_autofix.sql'),
    ('069_plan_usage_snapshots.sql'),
    ('070_plan_usage_display.sql'),
    ('071_provider_key_agent_use.sql');
