#!/usr/bin/env bash
# One-time bootstrap of the PRIVATE tap repo Quantal-Labs-AI/homebrew-orcha.
# Seeds README + CI only — Formula/ is owned by the release workflow, which
# pushes rendered formulae on every vX.Y.Z tag (so the tap stays installable
# only after the first release exists).
#
# Requires: `gh` authenticated with rights to create org repos, and SSH push
# access to the new repo. Safe to re-run: repo creation is skipped if it
# exists; the seed push is a plain commit (no force).
set -euo pipefail

ORG="Quantal-Labs-AI"
TAP_REPO="homebrew-orcha"
HERE="$(cd "$(dirname "$0")" && pwd)"
command -v gh >/dev/null || { echo "error: gh (GitHub CLI) is required and must be authenticated" >&2; exit 1; }

gh repo view "$ORG/$TAP_REPO" >/dev/null 2>&1 || {
  echo "creating private repo $ORG/$TAP_REPO ..."
  gh repo create "$ORG/$TAP_REPO" --private \
    -d "Private Homebrew tap for the orcha CLI (formulae are generated by the release workflow)"
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
git clone "git@github.com:$ORG/$TAP_REPO.git" "$WORK/tap"
cp -R "$HERE/tap-seed/." "$WORK/tap/"
git -C "$WORK/tap" add -A
if git -C "$WORK/tap" diff --cached --quiet; then
  echo "tap already seeded — nothing to push"
else
  git -C "$WORK/tap" commit -m "seed tap: README + CI (formulae arrive with the first release)"
  git -C "$WORK/tap" push origin HEAD:main
fi
echo "✓ tap ready: https://github.com/$ORG/$TAP_REPO"
echo "  next: add TAP_GITHUB_TOKEN secret to $ORG/Orcha, then tag v0.2.0"
